
language: r
warnings_are_errors: true
cache: packages

matrix:
  include:
  - r: devel
    env: BOXR_PASSWORD=''
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    env: BOXR_PASSWORD=''
  - r: oldrel
    env: BOXR_PASSWORD=''

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - find . -name testthat.Rout | xargs cat
  - Rscript -e 'library(covr);coveralls()'

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev
    - libgit2-dev
  